# Generated by Django 5.2.13 on 2026-04-12 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_role_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Discord Role ID')),
                ('name', models.CharField(max_length=255, verbose_name='Role Name')),
            ],
            options={
                'verbose_name': 'Discord Role',
                'verbose_name_plural': 'Discord Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiscordRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Django Group')),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ffdiscord.discordrole', verbose_name='Discord Role')),
            ],
            options={
                'verbose_name': 'Discord Role Mapping',
                'verbose_name_plural': 'Discord Role Mappings',
            },
        ),
    ]
