# Generated by Django 5.2.13 on 2026-04-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffdiscord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordrolemapping',
            name='grants_staff_access',
            field=models.BooleanField(default=False, help_text='Users with this role will have is_staff=True', verbose_name='Grants admin site access'),
        ),
    ]
