sonar.projectKey=fragforce_fragforce.org
sonar.organization=fragforce

# Ignore duplicate code blocks in the overlay files
sonar.cpd.exclusions=ffsite/static/ffsite/overlays/**

# Ignore dev SQL file entirely
sonar.exclusions=dev/ffsfdc.sql,**/migrations/**

# Coverage
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.10
