import random

# Words of exactly 3 syllables for stream key generation
WORDS = [
    # Adjectives
    "Beautiful", "Boisterous", "Bountiful", "Cavernous", "Chivalrous",
    "Colorful", "Comical", "Confident", "Cynical", "Dangerous",
    "Delicate", "Desperate", "Difficult", "Diligent", "Dominant",
    "Elegant", "Fabulous", "Ferocious", "Fictional", "Fluttering",
    "Fortunate", "Generous", "Glimmering", "Glittering", "Glorious",
    "Governing", "Hammering", "Harrowing", "Heavenly", "Hesitant",
    "Horrible", "Hovering", "Humorous", "Ignorant", "Imminent",
    "Innocent", "Jubilant", "Liberal", "Luminous", "Magical",
    "Masterful", "Merciful", "Militant", "Mystical", "Numerous",
    "Obvious", "Obstinate", "Ominous", "Outrageous", "Perilous",
    "Physical", "Plentiful", "Poisonous", "Popular", "Powerful",
    "Primitive", "Prominent", "Prosperous", "Radiant", "Reckoning",
    "Resonant", "Rigorous", "Riveting", "Scattering", "Shattering",
    "Shimmering", "Sinister", "Slithering", "Smoldering", "Spirited",
    "Staggering", "Suffering", "Summoning", "Sweltering", "Thundering",
    "Thunderous", "Towering", "Treacherous", "Turbulent", "Various",
    "Venomous", "Vigorous", "Vigilant", "Virulent", "Voracious",
    "Wandering", "Wavering", "Withering", "Wonderful",
    # Nouns - animals
    "Albatross", "Buffalo", "Bumblebee", "Butterfly", "Cardinal",
    "Caribou", "Chimpanzee", "Cockatoo", "Crocodile", "Dinosaur",
    "Dragonfly", "Elephant", "Flamingo", "Gorilla", "Hurricane",
    "Iguana", "Jaguar", "Jellyfish", "Katydid", "Kinkajou",
    "Labrador", "Manatee", "Mockingbird", "Monitor", "Ocelot",
    "Octopus", "Parakeet", "Pelican", "Peregrine", "Platypus",
    "Porcupine", "Predator", "Scorpion", "Wildebeest", "Wolverine",
    # Nouns - other
    "Acrobat", "Afterglow", "Alchemy", "Ambition", "Arsenal",
    "Artisan", "Avalanche", "Balcony", "Barricade", "Battery",
    "Bonanza", "Calendar", "Canopy", "Caravan", "Carnival",
    "Cathedral", "Caviar", "Celery", "Centipede", "Champion",
    "Character", "Cinnamon", "Citadel", "Clarity", "Coconut",
    "Colony", "Comedy", "Computer", "Corridor", "Covenant",
    "Cucumber", "Currency", "Cylinder", "Diamond", "Disaster",
    "Dominion", "Dynasty", "Echelon", "Effigy", "Emerald",
    "Embassy", "Encounter", "Endeavor", "Energy", "Erosion",
    "Evergreen", "Evidence", "Fantasy", "Festival", "Fiesta",
    "Filament", "Firmament", "Foundation", "Frequency", "Fugitive",
    "Galaxy", "Gallantry", "Garrison", "Genesis", "Gossamer",
    "Governor", "Gravity", "Grenadier", "Guarantee", "Harmony",
    "Heritage", "Hologram", "Horizon", "Hyena", "Illusion",
    "Imposter", "Infamy", "Interval", "Ivory", "Javelin",
    "Jealousy", "Jeopardy", "Jupiter", "Labyrinth", "Lavender",
    "Liberty", "Lollipop", "Lottery", "Loyalty", "Lullaby",
    "Magistrate", "Malady", "Manifold", "Marathon", "Mariner",
    "Masquerade", "Mastery", "Medicine", "Melody", "Memory",
    "Mercury", "Metaphor", "Meteor", "Mineral", "Miracle",
    "Misery", "Molecule", "Momentum", "Monument", "Mulberry",
    "Mystery", "Nebula", "November", "Obstacle", "Odyssey",
    "Offering", "Opulent", "Oracle", "Orchestra", "Ornament",
    "Oxygen", "Paragon", "Parachute", "Paradise", "Parody",
    "Passenger", "Patriot", "Patronage", "Pendulum", "Pentagon",
    "Pilgrimage", "Pioneer", "Polaris", "Pottery", "Poverty",
    "Prophecy", "Providence", "Pyramid", "Quarantine", "Radiance",
    "Reckoning", "Register", "Remedy", "Resonance", "Rhetoric",
    "Rhapsody", "Rivalry", "Rosary", "Samurai", "Satellite",
    "Savannah", "Scavenger", "Scenery", "Silhouette", "Skeleton",
    "Solitude", "Sorcerer", "Strategy", "Subtlety", "Sunflower",
    "Survivor", "Symphony", "Tapestry", "Telegram", "Telescope",
    "Temperate", "Tomorrow", "Tornado", "Torpedo", "Tradition",
    "Tragedy", "Traveler", "Treachery", "Triangle", "Tribunal",
    "Trinity", "Umbrella", "Universe", "Uprising", "Veteran",
    "Victory", "Vigilance", "Vinegar", "Visitor", "Volcano",
    "Wanderer", "Waterfall", "Wilderness", "Willpower", "Yesterday",
    "Zeppelin",
]


def generate_stream_key():
    """Generate a stream key as 4 capitalized 3-syllable words."""
    return "".join(random.choices(WORDS, k=4))
