# Generated by Django 5.2.12 on 2026-04-03 15:59

import django.contrib.postgres.fields.hstore
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventer', '0002_initial'),
        ('evtsignup', '0001_exts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(default='')),
                ('rank', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordEventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interest_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.interestlevel')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.CreateModel(
            name='ExtraLifeEventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_participant_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesforceEventUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StreamSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_players', models.PositiveSmallIntegerField(default=1)),
                ('max_players', models.PositiveSmallIntegerField(default=1)),
                ('ideal_players', models.PositiveSmallIntegerField(default=1)),
                ('flags', django.contrib.postgres.fields.hstore.HStoreField(default=dict)),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.game')),
                ('suggested_players', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameInterestUserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.game')),
                ('interest_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.interestlevel')),
            ],
            options={
                'unique_together': {('event_interest', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameInterestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interest_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.interestlevel')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
        migrations.CreateModel(
            name='EventRoleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
                ('event_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.eventrole')),
                ('interest_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.interestlevel')),
            ],
            options={
                'unique_together': {('event_interest', 'event_role')},
            },
        ),
        migrations.CreateModel(
            name='EventAvailabilityInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
                ('interest_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.interestlevel')),
            ],
            options={
                'unique_together': {('event_interest', 'period_start', 'period_end')},
            },
        ),
    ]
