# Generated by Django 5.2.13 on 2026-04-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscordEventUser',
        ),
    ]
