# Generated by Django 5.2.13 on 2026-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordeventuser',
            name='discord_display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Discord Display Name'),
        ),
    ]
