# Generated by Django 5.2.13 on 2026-04-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0003_remove_discordeventuser'),
        ('ffdonations', '0027_remove_tiltify_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventavailabilityinterest',
            name='event_role_interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventroleinterest'),
        ),
        migrations.AlterUniqueTogether(
            name='eventavailabilityinterest',
            unique_together={('event_role_interest', 'period_start', 'period_end')},
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventroleinterest',
            name='el_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ffdonations.participantmodel'),
        ),
        migrations.AddField(
            model_name='eventroleinterest',
            name='fundraising_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventroleinterest',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ExtraLifeEventUser',
        ),
        migrations.RemoveField(
            model_name='eventavailabilityinterest',
            name='event_interest',
        ),
    ]
