# Generated by Django 5.2.13 on 2026-04-17 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0003_remove_discordeventuser'),
        ('ffdonations', '0027_remove_tiltify_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extralifeeventuser',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='gameinterestuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='gameinterestuser',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameinterestuser',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='gameinterestuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='streamsuggestion',
            name='event_interest',
        ),
        migrations.RemoveField(
            model_name='streamsuggestion',
            name='game',
        ),
        migrations.RemoveField(
            model_name='streamsuggestion',
            name='suggested_players',
        ),
        migrations.AddField(
            model_name='eventavailabilityinterest',
            name='as_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventavailabilityinterest',
            name='as_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventavailabilityinterest',
            name='as_streamer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventavailabilityinterest',
            name='as_tech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventavailabilityinterest',
            name='hour',
            field=models.DateTimeField(default='2025-01-01 00:00:00'),
        ),
        migrations.AlterUniqueTogether(
            name='eventavailabilityinterest',
            unique_together={('event_interest', 'hour')},
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='el_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ffdonations.participantmodel'),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='fundraising_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='participant_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='preferences',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventinterest',
            name='streamer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='EventRoleInterest',
        ),
        migrations.DeleteModel(
            name='ExtraLifeEventUser',
        ),
        migrations.DeleteModel(
            name='GameInterestUser',
        ),
        migrations.DeleteModel(
            name='StreamSuggestion',
        ),
        migrations.RemoveField(
            model_name='eventavailabilityinterest',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='eventavailabilityinterest',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='eventavailabilityinterest',
            name='period_start',
        ),
    ]
