# Generated by Django 5.2.13 on 2026-04-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0004_signup_form_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventavailabilityinterest',
            name='hour',
            field=models.DateTimeField(),
        ),
    ]
