# Generated by Django 5.2.13 on 2026-04-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0005_remove_hour_default'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesforceEventUser',
        ),
    ]
