# Generated by Django 5.2.13 on 2026-04-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0006_remove_salesforceeventuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinterest',
            name='interest_level',
        ),
        migrations.RemoveField(
            model_name='gameinterestuserevent',
            name='interest_level',
        ),
        migrations.DeleteModel(
            name='InterestLevel',
        ),
    ]
