# Generated by Django 5.2.13 on 2026-04-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0011_event_signup_flags'),
        ('evtsignup', '0007_remove_interest_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameinterestuserevent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameinterestuserevent',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventer.eventrole'),
        ),
        migrations.AlterUniqueTogether(
            name='gameinterestuserevent',
            unique_together={('event_interest', 'game', 'role')},
        ),
    ]
