# Generated by Django 5.2.13 on 2026-05-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evtsignup', '0010_game_interest_role_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinterest',
            name='url_resolution_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times fundraising URL resolution has been attempted'),
        ),
    ]
