# Generated by Django 5.2.13 on 2026-05-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0028_eventrole_display_order_data'),
        ('evtsignup', '0011_url_resolution_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAvailabilityHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.eventrole')),
            ],
            options={
                'unique_together': {('event_interest', 'hour', 'role')},
            },
        ),
    ]
