# Generated by Django 5.2.13 on 2026-05-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0038_eventrole_show_notes_data'),
        ('evtsignup', '0014_drop_eventavailabilityinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInterestNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('event_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evtsignup.eventinterest')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.eventrole')),
            ],
            options={
                'unique_together': {('event_interest', 'role')},
            },
        ),
    ]
