# Generated by Django 5.2.13 on 2026-04-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffstream', '0006_alter_key_options_key_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={},
        ),
    ]
