# Generated by Django 5.2.13 on 2026-04-08 13:54

from django.db import migrations


def remove_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    Permission.objects.filter(codename='view_own_stream_key').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('ffstream', '0007_alter_key_options'),
    ]

    operations = [
        migrations.RunPython(remove_permission, migrations.RunPython.noop),
    ]
