# Generated by Django 5.2.13 on 2026-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffstream', '0008_remove_view_own_stream_key_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Can be used for Super Stream events'),
        ),
        migrations.AlterField(
            model_name='key',
            name='id',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False, verbose_name='Stream Key'),
        ),
        migrations.AlterField(
            model_name='key',
            name='name',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='key',
            name='pull',
            field=models.BooleanField(blank=True, default=False, verbose_name='Can be used as a viewer key to watch streams'),
        ),
    ]
