# Generated by Django 5.2.13 on 2026-04-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffstream', '0010_alter_key_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='key',
            old_name='active',
            new_name='superstream',
        ),
    ]
