# Generated by Django 5.2.13 on 2026-04-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffstream', '0011_rename_active_key_superstream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='superstream',
            field=models.BooleanField(blank=True, default=False, verbose_name='Can be used for Super Stream events'),
        ),
    ]
