# Generated by Django 5.2.13 on 2026-04-10 14:36
# State-only migration: the integer id PK was already created by 0016_key_swap_pk_to_integer raw SQL.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffstream', '0016_key_swap_pk_to_integer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='key',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
            database_operations=[],  # Already handled by 0016 raw SQL
        ),
    ]
