# Generated by Django 5.2.13 on 2026-04-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffstream', '0017_alter_key_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'permissions': [('set_key_livestream', 'Can set the livestream flag on stream keys'), ('set_key_superstream', 'Can set the superstream flag on stream keys')]},
        ),
    ]
