# Generated by Django 5.2.13 on 2026-04-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='igdb_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
