# Generated by Django 5.2.13 on 2026-04-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0003_game_igdb_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_cover_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='multiplayer_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
