# Generated by Django 5.2.13 on 2026-04-20 20:40

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0004_game_igdb_cache_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected - not allowed on stream (e.g. banned on Twitch)')], db_index=True, default='pending', help_text='Moderation status - rejected games cannot be selected on signup forms', max_length=20, verbose_name='Status'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='coordinator_notes',
            field=models.TextField(blank=True, help_text='Internal notes for coordinators, e.g. hardware requirements or known issues', verbose_name='Coordinator notes'),
        ),
        migrations.AddField(
            model_name='game',
            name='suggested',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this game on the signup form game selection list (only applies when status=approved)', verbose_name='Suggested game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='flags',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict, verbose_name='Flags'),
        ),
        migrations.AlterField(
            model_name='game',
            name='igdb_cover_hash',
            field=models.CharField(blank=True, help_text='IGDB image hash - use //images.igdb.com/igdb/image/upload/t_{size}/{hash}.jpg', max_length=255, null=True, verbose_name='IGDB cover hash'),
        ),
        migrations.AlterField(
            model_name='game',
            name='igdb_id',
            field=models.PositiveIntegerField(help_text='Numeric IGDB game ID, e.g. 115555', unique=True, verbose_name='IGDB ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='igdb_slug',
            field=models.SlugField(blank=True, help_text="IGDB URL slug, e.g. 'going-medieval'", max_length=255, null=True, unique=True, verbose_name='IGDB slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='igdb_url',
            field=models.URLField(blank=True, help_text='Full IGDB game page URL', null=True, verbose_name='IGDB URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='multiplayer_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum number of players; null=unknown, 1=single player only', null=True, verbose_name='Max players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(help_text='Internal URL slug for this app', max_length=255, unique=True, verbose_name='Fragforce slug'),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, help_text='Short game description from IGDB', verbose_name='IGDB summary'),
        ),
        migrations.DeleteModel(
            name='GameStatus',
        ),
    ]
