# Generated by Django 5.2.13 on 2026-04-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0005_game_status_choices_and_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text='IANA timezone name for coordinator-facing display (e.g. America/New_York). Public schedule uses browser local time via the |localtime template filter.', max_length=64),
        ),
    ]
