# Generated by Django 5.2.13 on 2026-04-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0006_event_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='flags',
        ),
    ]
