# Generated by Django 5.2.13 on 2026-04-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0007_game_remove_flags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_info',
        ),
    ]
