# Generated by Django 5.2.13 on 2026-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0008_team_remove_team_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=models.CharField(choices=[('US/Canada', [('America/New_York', 'Eastern (ET)'), ('America/Chicago', 'Central (CT)'), ('America/Denver', 'Mountain (MT)'), ('America/Los_Angeles', 'Pacific (PT)'), ('America/Anchorage', 'Alaska (AKT)'), ('Pacific/Honolulu', 'Hawaii (HT)')]), ('Australia/NZ', [('Australia/Sydney', 'Sydney/Melbourne (AEST)'), ('Australia/Brisbane', 'Brisbane (AEST no DST)'), ('Australia/Perth', 'Perth (AWST)'), ('Pacific/Auckland', 'Auckland (NZST)')]), ('Europe/UK', [('Europe/London', 'London (GMT/BST)'), ('Europe/Paris', 'Central Europe (CET/CEST)'), ('Europe/Helsinki', 'Eastern Europe (EET/EEST)')]), ('Other', [('UTC', 'UTC'), ('Asia/Singapore', 'Singapore (SGT)'), ('Asia/Tokyo', 'Japan (JST)')])], default='America/New_York', help_text='Timezone for coordinator-facing display. Public schedule uses browser local time via the |localtime template filter.', max_length=64),
        ),
    ]
