# Generated by Django 5.2.13 on 2026-04-21 22:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0009_alter_event_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignupSlotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_block_hours', models.PositiveSmallIntegerField(default=3, help_text='Default slot block size in hours for participant/streamer grid')),
                ('prime_block_hours', models.PositiveSmallIntegerField(default=2, help_text='Slot block size during prime time hours')),
                ('prime_time_start', models.TimeField(default=datetime.time(14, 0), help_text='Start of prime time (in event timezone) - shorter blocks begin here')),
                ('prime_time_end', models.TimeField(default=datetime.time(21, 0), help_text='End of prime time (in event timezone) - shorter blocks end here')),
                ('management_block_hours', models.PositiveSmallIntegerField(default=6, help_text='Block size in hours for moderator and tech manager slots')),
                ('mod_first_block_hours', models.PositiveSmallIntegerField(default=3, help_text='Length of the first moderator block - shorter than standard to stagger mod/tech changeovers')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot_config', to='eventer.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventSignupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Slot start time (UTC)')),
                ('stop', models.DateTimeField(help_text='Slot end time (UTC)')),
                ('label', models.CharField(help_text='Human-readable label shown on signup form', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_slots', to='eventer.event')),
                ('roles', models.ManyToManyField(blank=True, help_text='Roles this slot applies to', to='eventer.eventrole')),
            ],
            options={
                'ordering': ['start'],
                'unique_together': {('event', 'start', 'stop')},
            },
        ),
    ]
