# Generated by Django 5.2.13 on 2026-04-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0010_signup_slot_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='edits_open',
            field=models.BooleanField(default=False, help_text='Allow existing signups to be edited. Has no effect when locked.'),
        ),
        migrations.AddField(
            model_name='event',
            name='locked',
            field=models.BooleanField(default=False, help_text='Lock the event - disables all signups and edits regardless of other flags.'),
        ),
        migrations.AddField(
            model_name='event',
            name='signups_open',
            field=models.BooleanField(default=False, help_text='Allow new signups. Has no effect when locked.'),
        ),
    ]
