# Generated by Django 5.2.13 on 2026-04-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0011_event_signup_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.BooleanField(default=False, help_text='Show this event on the public events listing.'),
        ),
    ]
