# Generated by Django 5.2.13 on 2026-04-24 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0012_event_public_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule_published',
            field=models.BooleanField(default=False, help_text='Publish the finalized schedule - enables the public schedule view.'),
        ),
        migrations.CreateModel(
            name='EventScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='eventer.event')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.eventrole')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='eventer.eventsignupslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot__start', 'role__name'],
                'unique_together': {('slot', 'role')},
            },
        ),
    ]
