# Generated by Django 5.2.13 on 2026-04-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0013_schedule_slot_and_published_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='color',
            field=models.CharField(default='#417690', help_text='Hex color code for UI display (e.g. #417690)', max_length=7),
        ),
    ]
