# Generated by Django 5.2.13 on 2026-04-27 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0014_eventrole_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_coordinator_schedule', 'Can view the coordinator schedule for events')]},
        ),
    ]
