# Generated by Django 5.2.13 on 2026-04-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0015_event_coordinator_schedule_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventscheduleslot',
            name='game',
            field=models.ForeignKey(blank=True, help_text='Game being played this slot (streamer slots only)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventer.game'),
        ),
    ]
