# Generated by Django 5.2.13 on 2026-04-29 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0016_eventscheduleslot_add_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScheduleMultiAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_multi_assignments', to='eventer.event')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventer.eventrole')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_assignments', to='eventer.eventsignupslot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['slot__start', 'role__name'],
                'unique_together': {('slot', 'role', 'user')},
            },
        ),
    ]
