# Generated by Django 5.2.13 on 2026-04-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0018_rename_eventscheduleslot_to_eventscheduleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='first_release_date',
            field=models.DateField(blank=True, help_text='Initial release date from IGDB', null=True, verbose_name='First release date'),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_category',
            field=models.PositiveSmallIntegerField(blank=True, help_text='IGDB game category: 0=main game, 1=DLC, 2=expansion, 3=bundle, 4=standalone expansion', null=True, verbose_name='IGDB category'),
        ),
    ]
