# Generated by Django 5.2.13 on 2026-04-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0019_igdb_game_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
