# Generated by Django 5.2.13 on 2026-04-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0020_remove_game_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'permissions': [('search_igdb', 'Can search IGDB and sync games')]},
        ),
    ]
