# Generated by Django 5.2.13 on 2026-04-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0021_game_search_igdb_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Game name'),
        ),
    ]
