# Generated by Django 5.2.13 on 2026-04-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0022_remove_game_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='multiplayer_max_override',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Manual override for max players; takes precedence over IGDB value when set', null=True, verbose_name='Max players (override)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='multiplayer_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum co-op party size from IGDB; null=unknown or single player', null=True, verbose_name='Max players (IGDB)'),
        ),
    ]
