# Generated by Django 5.2.13 on 2026-05-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0024_seed_superstream_eventroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='multi_assign',
            field=models.BooleanField(default=False, help_text='Allow multiple users assigned per slot (e.g. Participant). Single-assign roles enforce one user per slot.'),
        ),
    ]
