# Generated by Django 5.2.13 on 2026-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0026_eventrole_multi_assign_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventrole',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='eventrole',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=100, help_text='Display order — lower numbers appear first. Roles with the same value are sorted alphabetically.'),
        ),
    ]
