# Generated by Django 5.2.13 on 2026-05-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0028_eventrole_display_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='game_min_players',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Exclude games where max players is less than this value. Leave blank to show all games.', null=True),
        ),
        migrations.AddField(
            model_name='eventrole',
            name='has_game_selection',
            field=models.BooleanField(default=False, help_text='Show a game preference picker for this role on the signup form.'),
        ),
    ]
