# Generated by Django 5.2.13 on 2026-05-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0030_eventrole_game_selection_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='show_fundraising_url',
            field=models.BooleanField(default=False, help_text='Show the fundraising URL field for this role on the signup form.'),
        ),
    ]
