# Generated by Django 5.2.13 on 2026-05-05 17:25

import django.db.models.deletion
from django.db import migrations, models


def assert_mod_first_block_hours_default(apps, schema_editor):
    EventSignupSlotConfig = apps.get_model('eventer', 'EventSignupSlotConfig')
    non_default = list(
        EventSignupSlotConfig.objects.exclude(mod_first_block_hours=3)
        .values_list('event_id', 'mod_first_block_hours')
    )
    if non_default:
        raise ValueError(
            f"Cannot drop mod_first_block_hours: non-default values found in EventSignupSlotConfig: {non_default}. "
            "Migrate these values to EventSlotGroupMembership.first_block_hours first."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0032_eventrole_show_fundraising_url_data'),
    ]

    operations = [
        migrations.RunPython(assert_mod_first_block_hours_default, migrations.RunPython.noop),
        migrations.CreateModel(
            name='EventSlotGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('use_prime_time', models.BooleanField(default=False, help_text="If true, use variable prime-time block sizing. If false, use this group's block_hours (or the event's management_block_hours if not set).")),
                ('block_hours', models.PositiveSmallIntegerField(blank=True, help_text="Block size in hours for this group. Null falls back to the event's management_block_hours. Ignored when use_prime_time is true.", null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventsignupslotconfig',
            name='mod_first_block_hours',
        ),
        migrations.AlterField(
            model_name='eventsignupslotconfig',
            name='management_block_hours',
            field=models.PositiveSmallIntegerField(default=6, help_text='Default block size in hours for management-style role groups. Individual groups can override this.'),
        ),
        migrations.CreateModel(
            name='EventSlotGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_block_hours', models.PositiveSmallIntegerField(blank=True, help_text="Override the first slot's block size for this role to stagger changeovers. Null uses the group's standard block size.", null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='eventer.eventslotgroup')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_group_memberships', to='eventer.eventrole')),
            ],
            options={
                'unique_together': {('group', 'role')},
            },
        ),
        migrations.AddField(
            model_name='eventslotgroup',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='slot_groups', through='eventer.EventSlotGroupMembership', to='eventer.eventrole'),
        ),
    ]
