# Generated by Django 5.2.13 on 2026-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0034_slot_groups_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='show_stream_commands',
            field=models.BooleanField(default=False, help_text="Show Twitch stream commands (title, game, donate) in the coordinator schedule for this role. Also pins this role's column first."),
        ),
    ]
