# Generated by Django 5.2.13 on 2026-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventer', '0036_eventrole_show_stream_commands_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrole',
            name='show_notes',
            field=models.BooleanField(default=False, help_text="Show an 'Other game preferences' notes textarea for this role on the signup form."),
        ),
    ]
